ASP.NET.PracticeOne/ASP.NET.Homework1/Models/Equipment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASP.NET.Homework1.Models
{
    public class Equipment
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string AssignedTo { get; set; }
    }
}

ASP.NET.PracticeOne/ASP.NET.Homework1/Controllers/EquipmentController.cs
using ASP.NET.Homework1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP.NET.Homework1.Controllers
{
    //[Authorize]
    public class EquipmentController : Controller
    {
        Database db = new Database();

        public ActionResult Index(string query)
        {
            List<Equipment> equipment = db.GetEquipment();

            //for <span>assigness></span>
            if (equipment.Count() == 0)
            {
                ViewBag.Assigness = 0;

                int stf = ViewBag.Assigness;
            }

            for (int i = 0; i < equipment.Count; i++)
            {
                if (!string.IsNullOrEmpty(query) && equipment[i].AssignedTo.ToLower() == query.ToLower())
                {
                    var equipmentAssignedTo = equipment.Where(x => x.AssignedTo.ToLower().Equals(query.ToLower())).ToList();

                    return View(equipmentAssignedTo);
                }
            }

            if((!string.IsNullOrEmpty(query)))
                {

                var listString = query.Split().ToList();
                var joinedQuery = string.Join("", listString.ToArray());
                var equipmentSearched = equipment.Where(x => x.Name.ToLower().Contains(joinedQuery.ToLower().Trim())).ToList();

                if (equipmentSearched.Count == 0)
                {
                    return RedirectToAction("Error");
                }

                return View(equipmentSearched);
                }

            // for adding buttons
            List<string> distinct = equipment.Select(x => x.AssignedTo).Distinct().ToList();
            ViewData["Distinct"] = distinct;

            return View(equipment);
        }

        public ActionResult Error()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Equipment item)
        {
            db.AddEquipment(item);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var equipmentItem = db.GetEquipment().FirstOrDefault(x => x.ID == id);

            return View(equipmentItem);
        }

        [HttpPost]
        public ActionResult Edit(Equipment item)
        {
            if (ModelState.IsValid)
            {
                db.EditEquipment(item);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var item = db.GetEquipment().FirstOrDefault(x => x.ID == id);

            return View(item);
        }

        [HttpPost]
        public ActionResult Delete(Equipment item)
        {
            db.DeleteEquipment(item);

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var item = db.GetEquipment().FirstOrDefault(x => x.ID == id);

            return View(item);
        }

	}
}

ASP.NET.PracticeOne/ASP.NET.Homework1/Views/Equipment/Create.cshtml
@model ASP.NET.Homework1.Models.Equipment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Equipment</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Category, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignedTo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AssignedTo, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssignedTo)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ASP.NET.PracticeOne/ASP.NET.Homework1/Views/Equipment/Delete.cshtml
@model ASP.NET.Homework1.Models.Equipment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Equipment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignedTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedTo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ASP.NET.PracticeOne/ASP.NET.Homework1/Views/Equipment/Details.cshtml
@model ASP.NET.Homework1.Models.Equipment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Equipment</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignedTo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedTo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ASP.NET.PracticeOne/ASP.NET.Homework1/Views/Equipment/Edit.cshtml
@model ASP.NET.Homework1.Models.Equipment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Equipment</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category)
                @Html.ValidationMessageFor(model => model.Category)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignedTo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AssignedTo)
                @Html.ValidationMessageFor(model => model.AssignedTo)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASP.NET.PracticeOne/ASP.NET.Homework1/Views/Equipment/Index.cshtml
@model IEnumerable<ASP.NET.Homework1.Models.Equipment>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form method="get" action="~/Equipment/Index" class="navbar-form navbar-left">
    <div class="form-group">
        <input type="text" class="form-control" name="query" placeholder="Search equipment">
    </div>
    <button type="submit" class="btn btn-default">Filter</button>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedTo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
           @Optimize(item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignedTo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}
</table>

@{
    var distinct = (List<string>)ViewData["Distinct"];
}


@if (Request.QueryString["query"] == null || Request.QueryString["query"] == "")
{

    
<span style="display:@Assigness()">Assignees:</span>
    for (int i = 0; i < distinct.Count; i++)
    {
        <form method="get" action="~/Equipment/Index" style="display:inline">
            <button class="btn" style="background-color: @Colorize()" name="query" value="@distinct[i]">@distinct[i]</button>
    </form>
    }
}

@if (Request.QueryString["query"] != null || Request.QueryString["query"] != "")
{ 
foreach (var item in Model) 
{
    if (Request.QueryString["query"] != null && item.AssignedTo.ToLower() == Request.QueryString["query"].ToLower())
    {
        <span>Filtered By:</span>
        <button class="btn" style="background-color: @Colorize()">@item.AssignedTo</button>
        @Html.ActionLink("(Reset)", "Index");
    break;
    }
    
    // if is searched by search form
    if (Request.QueryString["query"] != null && Request.QueryString["query"] != "")
    {
        @Html.ActionLink("<-- Back to List", "Index");
    break;
    }
}
}

@functions{

    Random number = new Random();

    public string Colorize()
    {
        string num = "#48b" + number.Next(0, 613);

        return num;
    }

    public string Optimize(string desc)
    {
        return desc.Count() > 20 ? desc.Substring(0, 20) + "..." : desc;
    }

    public string Assigness()
    {
        if (ViewBag.Assigness == 0)
        {
            return "none";
        }
        return "";
    }
}

ASP.NET.PracticeOne/ASP.NET.Homework1/Views/Equipment/Search.cshtml
@model IEnumerable<ASP.NET.Homework1.Models.Equipment>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form method="get" action="~/Equipment/Search" class="navbar-form navbar-left">
    <div class="form-group">
        <input type="text" class="form-control" name="query" placeholder="Search equipment">
    </div>
    <button type="submit" class="btn btn-default">Filter</button>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedTo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                 @Optimize(item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignedTo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>

@*@if (Request.QueryString["query"] != "" && Request.QueryString["query"] != null)
{
    @Html.ActionLink("<-- Back to List", "Index", "Equipment")    
}
else
{
    Response.Redirect(Url.Action("Index"));
}*@


    @*<span>Assignees:</span>
    @foreach (var item in Model)
    {
        <form method="get" action="~/Equipment/Index" style="display:inline">
            <button class="btn" style="background-color: @Colorize()" name="query" value="@item.AssignedTo">@item.AssignedTo</button>
        </form>
    }*@


@functions{

    Random number = new Random();

    public string Colorize()
    {
        string num = "#48b" + number.Next(0, 613);

        return num;
    }

    public string Optimize(string desc)
    {

        return desc.Count() > 20 ? desc.Substring(0, 20) + "..." : desc;
    }
}